// Code generated by mockery v2.53.5. DO NOT EDIT.

package auth

import (
	auth "circa/internal/service/auth"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// CompleteSignup provides a mock function with given fields: ctx, sessionID, address, signature, message
func (_m *MockAuthService) CompleteSignup(ctx context.Context, sessionID string, address string, signature string, message string) (*auth.CompleteSignupResult, error) {
	ret := _m.Called(ctx, sessionID, address, signature, message)

	if len(ret) == 0 {
		panic("no return value specified for CompleteSignup")
	}

	var r0 *auth.CompleteSignupResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*auth.CompleteSignupResult, error)); ok {
		return rf(ctx, sessionID, address, signature, message)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *auth.CompleteSignupResult); ok {
		r0 = rf(ctx, sessionID, address, signature, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.CompleteSignupResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, sessionID, address, signature, message)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_CompleteSignup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteSignup'
type MockAuthService_CompleteSignup_Call struct {
	*mock.Call
}

// CompleteSignup is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - address string
//   - signature string
//   - message string
func (_e *MockAuthService_Expecter) CompleteSignup(ctx interface{}, sessionID interface{}, address interface{}, signature interface{}, message interface{}) *MockAuthService_CompleteSignup_Call {
	return &MockAuthService_CompleteSignup_Call{Call: _e.mock.On("CompleteSignup", ctx, sessionID, address, signature, message)}
}

func (_c *MockAuthService_CompleteSignup_Call) Run(run func(ctx context.Context, sessionID string, address string, signature string, message string)) *MockAuthService_CompleteSignup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockAuthService_CompleteSignup_Call) Return(_a0 *auth.CompleteSignupResult, _a1 error) *MockAuthService_CompleteSignup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_CompleteSignup_Call) RunAndReturn(run func(context.Context, string, string, string, string) (*auth.CompleteSignupResult, error)) *MockAuthService_CompleteSignup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLoginMagicLink provides a mock function with given fields: ctx, email
func (_m *MockAuthService) CreateLoginMagicLink(ctx context.Context, email string) (*auth.LoginResult, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for CreateLoginMagicLink")
	}

	var r0 *auth.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.LoginResult, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.LoginResult); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.LoginResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_CreateLoginMagicLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLoginMagicLink'
type MockAuthService_CreateLoginMagicLink_Call struct {
	*mock.Call
}

// CreateLoginMagicLink is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthService_Expecter) CreateLoginMagicLink(ctx interface{}, email interface{}) *MockAuthService_CreateLoginMagicLink_Call {
	return &MockAuthService_CreateLoginMagicLink_Call{Call: _e.mock.On("CreateLoginMagicLink", ctx, email)}
}

func (_c *MockAuthService_CreateLoginMagicLink_Call) Run(run func(ctx context.Context, email string)) *MockAuthService_CreateLoginMagicLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_CreateLoginMagicLink_Call) Return(_a0 *auth.LoginResult, _a1 error) *MockAuthService_CreateLoginMagicLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_CreateLoginMagicLink_Call) RunAndReturn(run func(context.Context, string) (*auth.LoginResult, error)) *MockAuthService_CreateLoginMagicLink_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePendingSignup provides a mock function with given fields: ctx, fullName, email, displayName
func (_m *MockAuthService) CreatePendingSignup(ctx context.Context, fullName string, email string, displayName *string) (*auth.SignupResult, error) {
	ret := _m.Called(ctx, fullName, email, displayName)

	if len(ret) == 0 {
		panic("no return value specified for CreatePendingSignup")
	}

	var r0 *auth.SignupResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string) (*auth.SignupResult, error)); ok {
		return rf(ctx, fullName, email, displayName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *string) *auth.SignupResult); ok {
		r0 = rf(ctx, fullName, email, displayName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.SignupResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *string) error); ok {
		r1 = rf(ctx, fullName, email, displayName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_CreatePendingSignup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePendingSignup'
type MockAuthService_CreatePendingSignup_Call struct {
	*mock.Call
}

// CreatePendingSignup is a helper method to define mock.On call
//   - ctx context.Context
//   - fullName string
//   - email string
//   - displayName *string
func (_e *MockAuthService_Expecter) CreatePendingSignup(ctx interface{}, fullName interface{}, email interface{}, displayName interface{}) *MockAuthService_CreatePendingSignup_Call {
	return &MockAuthService_CreatePendingSignup_Call{Call: _e.mock.On("CreatePendingSignup", ctx, fullName, email, displayName)}
}

func (_c *MockAuthService_CreatePendingSignup_Call) Run(run func(ctx context.Context, fullName string, email string, displayName *string)) *MockAuthService_CreatePendingSignup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*string))
	})
	return _c
}

func (_c *MockAuthService_CreatePendingSignup_Call) Return(_a0 *auth.SignupResult, _a1 error) *MockAuthService_CreatePendingSignup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_CreatePendingSignup_Call) RunAndReturn(run func(context.Context, string, string, *string) (*auth.SignupResult, error)) *MockAuthService_CreatePendingSignup_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateNonce provides a mock function with given fields: ctx, sessionID, address, chainID
func (_m *MockAuthService) GenerateNonce(ctx context.Context, sessionID string, address string, chainID *int64) (*auth.NonceResult, error) {
	ret := _m.Called(ctx, sessionID, address, chainID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateNonce")
	}

	var r0 *auth.NonceResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *int64) (*auth.NonceResult, error)); ok {
		return rf(ctx, sessionID, address, chainID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *int64) *auth.NonceResult); ok {
		r0 = rf(ctx, sessionID, address, chainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.NonceResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *int64) error); ok {
		r1 = rf(ctx, sessionID, address, chainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_GenerateNonce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateNonce'
type MockAuthService_GenerateNonce_Call struct {
	*mock.Call
}

// GenerateNonce is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - address string
//   - chainID *int64
func (_e *MockAuthService_Expecter) GenerateNonce(ctx interface{}, sessionID interface{}, address interface{}, chainID interface{}) *MockAuthService_GenerateNonce_Call {
	return &MockAuthService_GenerateNonce_Call{Call: _e.mock.On("GenerateNonce", ctx, sessionID, address, chainID)}
}

func (_c *MockAuthService_GenerateNonce_Call) Run(run func(ctx context.Context, sessionID string, address string, chainID *int64)) *MockAuthService_GenerateNonce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*int64))
	})
	return _c
}

func (_c *MockAuthService_GenerateNonce_Call) Return(_a0 *auth.NonceResult, _a1 error) *MockAuthService_GenerateNonce_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_GenerateNonce_Call) RunAndReturn(run func(context.Context, string, string, *int64) (*auth.NonceResult, error)) *MockAuthService_GenerateNonce_Call {
	_c.Call.Return(run)
	return _c
}

// GetSignupSession provides a mock function with given fields: ctx, sessionID
func (_m *MockAuthService) GetSignupSession(ctx context.Context, sessionID string) (map[string]interface{}, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSignupSession")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]interface{}, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]interface{}); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_GetSignupSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSignupSession'
type MockAuthService_GetSignupSession_Call struct {
	*mock.Call
}

// GetSignupSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockAuthService_Expecter) GetSignupSession(ctx interface{}, sessionID interface{}) *MockAuthService_GetSignupSession_Call {
	return &MockAuthService_GetSignupSession_Call{Call: _e.mock.On("GetSignupSession", ctx, sessionID)}
}

func (_c *MockAuthService_GetSignupSession_Call) Run(run func(ctx context.Context, sessionID string)) *MockAuthService_GetSignupSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_GetSignupSession_Call) Return(_a0 map[string]interface{}, _a1 error) *MockAuthService_GetSignupSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_GetSignupSession_Call) RunAndReturn(run func(context.Context, string) (map[string]interface{}, error)) *MockAuthService_GetSignupSession_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyToken provides a mock function with given fields: ctx, token
func (_m *MockAuthService) VerifyToken(ctx context.Context, token string) (*auth.VerifyTokenResult, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 *auth.VerifyTokenResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.VerifyTokenResult, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.VerifyTokenResult); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.VerifyTokenResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type MockAuthService_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthService_Expecter) VerifyToken(ctx interface{}, token interface{}) *MockAuthService_VerifyToken_Call {
	return &MockAuthService_VerifyToken_Call{Call: _e.mock.On("VerifyToken", ctx, token)}
}

func (_c *MockAuthService_VerifyToken_Call) Run(run func(ctx context.Context, token string)) *MockAuthService_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_VerifyToken_Call) Return(_a0 *auth.VerifyTokenResult, _a1 error) *MockAuthService_VerifyToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_VerifyToken_Call) RunAndReturn(run func(context.Context, string) (*auth.VerifyTokenResult, error)) *MockAuthService_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
