// Code generated by mockery v2.53.5. DO NOT EDIT.

package email

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEmailService is an autogenerated mock type for the EmailService type
type MockEmailService struct {
	mock.Mock
}

type MockEmailService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailService) EXPECT() *MockEmailService_Expecter {
	return &MockEmailService_Expecter{mock: &_m.Mock}
}

// SendMagicLink provides a mock function with given fields: ctx, toEmail, toName, magicLinkURL
func (_m *MockEmailService) SendMagicLink(ctx context.Context, toEmail string, toName string, magicLinkURL string) error {
	ret := _m.Called(ctx, toEmail, toName, magicLinkURL)

	if len(ret) == 0 {
		panic("no return value specified for SendMagicLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, toEmail, toName, magicLinkURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmailService_SendMagicLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMagicLink'
type MockEmailService_SendMagicLink_Call struct {
	*mock.Call
}

// SendMagicLink is a helper method to define mock.On call
//   - ctx context.Context
//   - toEmail string
//   - toName string
//   - magicLinkURL string
func (_e *MockEmailService_Expecter) SendMagicLink(ctx interface{}, toEmail interface{}, toName interface{}, magicLinkURL interface{}) *MockEmailService_SendMagicLink_Call {
	return &MockEmailService_SendMagicLink_Call{Call: _e.mock.On("SendMagicLink", ctx, toEmail, toName, magicLinkURL)}
}

func (_c *MockEmailService_SendMagicLink_Call) Run(run func(ctx context.Context, toEmail string, toName string, magicLinkURL string)) *MockEmailService_SendMagicLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockEmailService_SendMagicLink_Call) Return(_a0 error) *MockEmailService_SendMagicLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmailService_SendMagicLink_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockEmailService_SendMagicLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailService creates a new instance of MockEmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailService {
	mock := &MockEmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
