// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionAuthScopes = "SessionAuth.Scopes"
)

// Defines values for ActivityItemType.
const (
	ActivityItemTypePayment ActivityItemType = "payment"
	ActivityItemTypePayout  ActivityItemType = "payout"
)

// Defines values for GroupMemberRole.
const (
	Member GroupMemberRole = "member"
	Owner  GroupMemberRole = "owner"
)

// Defines values for GroupMemberStatus.
const (
	Accepted GroupMemberStatus = "accepted"
	Invited  GroupMemberStatus = "invited"
	Removed  GroupMemberStatus = "removed"
)

// Defines values for InviteSummaryStatus.
const (
	InviteSummaryStatusActive  InviteSummaryStatus = "active"
	InviteSummaryStatusExpired InviteSummaryStatus = "expired"
	InviteSummaryStatusMaxed   InviteSummaryStatus = "maxed"
	InviteSummaryStatusRevoked InviteSummaryStatus = "revoked"
)

// Defines values for RoundStatus.
const (
	RoundStatusActive    RoundStatus = "active"
	RoundStatusCompleted RoundStatus = "completed"
	RoundStatusPending   RoundStatus = "pending"
)

// Defines values for RoundDetailStatus.
const (
	RoundDetailStatusActive    RoundDetailStatus = "active"
	RoundDetailStatusCompleted RoundDetailStatus = "completed"
	RoundDetailStatusPending   RoundDetailStatus = "pending"
)

// Defines values for RoundPeriodStatusStatus.
const (
	RoundPeriodStatusStatusActive    RoundPeriodStatusStatus = "active"
	RoundPeriodStatusStatusCompleted RoundPeriodStatusStatus = "completed"
	RoundPeriodStatusStatusPending   RoundPeriodStatusStatus = "pending"
)

// Defines values for RoundSummaryStatus.
const (
	RoundSummaryStatusActive    RoundSummaryStatus = "active"
	RoundSummaryStatusCompleted RoundSummaryStatus = "completed"
	RoundSummaryStatusPending   RoundSummaryStatus = "pending"
)

// Defines values for ListGroupRoundsParamsStatus.
const (
	ListGroupRoundsParamsStatusActive    ListGroupRoundsParamsStatus = "active"
	ListGroupRoundsParamsStatusCompleted ListGroupRoundsParamsStatus = "completed"
	ListGroupRoundsParamsStatusPending   ListGroupRoundsParamsStatus = "pending"
)

// Defines values for ListRoundsParamsStatus.
const (
	Active    ListRoundsParamsStatus = "active"
	Completed ListRoundsParamsStatus = "completed"
	Pending   ListRoundsParamsStatus = "pending"
)

// Defines values for GetRoundActivityParamsType.
const (
	GetRoundActivityParamsTypePayment GetRoundActivityParamsType = "payment"
	GetRoundActivityParamsTypePayout  GetRoundActivityParamsType = "payout"
)

// AcceptInviteRequest defines model for AcceptInviteRequest.
type AcceptInviteRequest struct {
	// Code Invite code
	Code string `json:"code"`
}

// AcceptInviteResponse defines model for AcceptInviteResponse.
type AcceptInviteResponse struct {
	GroupId UUID `json:"groupId"`
}

// ActivityItem defines model for ActivityItem.
type ActivityItem struct {
	// Address EVM address (0x-prefixed, 40 hex chars)
	Address *Address `json:"address,omitempty"`

	// Amount Amount in smallest units
	Amount      *string `json:"amount,omitempty"`
	BlockNumber *int    `json:"blockNumber"`
	Id          UUID    `json:"id"`

	// Period Period number this activity belongs to
	Period    *int      `json:"period"`
	Timestamp Timestamp `json:"timestamp"`

	// TransactionHash On-chain transaction hash
	TransactionHash *string          `json:"transactionHash,omitempty"`
	Type            ActivityItemType `json:"type"`
}

// ActivityItemType defines model for ActivityItem.Type.
type ActivityItemType string

// ActivityPage defines model for ActivityPage.
type ActivityPage struct {
	Items      []ActivityItem `json:"items"`
	NextCursor *string        `json:"nextCursor"`
}

// Address EVM address (0x-prefixed, 40 hex chars)
type Address = string

// AuthNonceRequest defines model for AuthNonceRequest.
type AuthNonceRequest struct {
	// Address EVM address (0x-prefixed, 40 hex chars)
	Address Address `json:"address"`

	// ChainId EVM chain id
	ChainId *ChainId `json:"chainId,omitempty"`
}

// AuthNonceResponse defines model for AuthNonceResponse.
type AuthNonceResponse struct {
	ExpiresAt Timestamp `json:"expiresAt"`

	// MessageTemplate Optional template the client can use to construct the sign-in message
	MessageTemplate *string `json:"messageTemplate,omitempty"`

	// Nonce One-time nonce used for wallet sign-in (hex-encoded)
	Nonce string `json:"nonce"`
}

// AuthVerifyRequest defines model for AuthVerifyRequest.
type AuthVerifyRequest struct {
	// Address EVM address (0x-prefixed, 40 hex chars)
	Address Address `json:"address"`

	// Message The exact message that was signed (must include nonce and domain binding)
	Message string `json:"message"`

	// Signature ECDSA signature of the message (hex-encoded, 0x-prefixed)
	Signature string `json:"signature"`
}

// AuthVerifyResponse defines model for AuthVerifyResponse.
type AuthVerifyResponse struct {
	User User `json:"user"`
}

// ChainId EVM chain id
type ChainId = int

// CreateGroupRequest defines model for CreateGroupRequest.
type CreateGroupRequest struct {
	AvatarUrl   *string `json:"avatarUrl,omitempty"`
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreateInviteRequest defines model for CreateInviteRequest.
type CreateInviteRequest struct {
	ExpiresAt *Timestamp `json:"expiresAt,omitempty"`
	MaxUses   *int       `json:"maxUses,omitempty"`
}

// CreateRoundRequest defines model for CreateRoundRequest.
type CreateRoundRequest struct {
	// ChainId EVM chain id
	ChainId ChainId `json:"chainId"`

	// ContractAddress EVM address (0x-prefixed, 40 hex chars)
	ContractAddress Address `json:"contractAddress"`

	// ContributionAmount Contribution amount in smallest units (string to avoid JSON number limits)
	ContributionAmount string `json:"contributionAmount"`

	// CurrencySymbol Optional currency symbol (e.g. USDC)
	CurrencySymbol *string `json:"currencySymbol,omitempty"`
}

// ErrorBadRequest defines model for ErrorBadRequest.
type ErrorBadRequest struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// ErrorForbidden defines model for ErrorForbidden.
type ErrorForbidden struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// ErrorInternalServerError defines model for ErrorInternalServerError.
type ErrorInternalServerError struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// ErrorNotFound defines model for ErrorNotFound.
type ErrorNotFound struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// ErrorUnauthorized defines model for ErrorUnauthorized.
type ErrorUnauthorized struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Group defines model for Group.
type Group struct {
	AvatarUrl   *string       `json:"avatarUrl"`
	CreatedAt   Timestamp     `json:"createdAt"`
	Description *string       `json:"description"`
	Id          UUID          `json:"id"`
	MemberCount int           `json:"memberCount"`
	Members     []GroupMember `json:"members"`
	Name        string        `json:"name"`

	// OwnerAddress EVM address (0x-prefixed, 40 hex chars)
	OwnerAddress Address    `json:"ownerAddress"`
	UpdatedAt    *Timestamp `json:"updatedAt,omitempty"`
}

// GroupMember defines model for GroupMember.
type GroupMember struct {
	// Address EVM address (0x-prefixed, 40 hex chars)
	Address     Address           `json:"address"`
	DisplayName *string           `json:"displayName"`
	JoinedAt    *Timestamp        `json:"joinedAt,omitempty"`
	Role        GroupMemberRole   `json:"role"`
	Status      GroupMemberStatus `json:"status"`
}

// GroupMemberRole defines model for GroupMember.Role.
type GroupMemberRole string

// GroupMemberStatus defines model for GroupMember.Status.
type GroupMemberStatus string

// GroupPage defines model for GroupPage.
type GroupPage struct {
	Items      []GroupSummary `json:"items"`
	NextCursor *string        `json:"nextCursor"`
}

// GroupSummary defines model for GroupSummary.
type GroupSummary struct {
	AvatarUrl   *string    `json:"avatarUrl"`
	CreatedAt   Timestamp  `json:"createdAt"`
	Description *string    `json:"description"`
	Id          UUID       `json:"id"`
	MemberCount int        `json:"memberCount"`
	Name        string     `json:"name"`
	UpdatedAt   *Timestamp `json:"updatedAt,omitempty"`
}

// Invite defines model for Invite.
type Invite struct {
	// Code Invite code (returned only at creation time)
	Code      string     `json:"code"`
	CreatedAt Timestamp  `json:"createdAt"`
	ExpiresAt *Timestamp `json:"expiresAt,omitempty"`
	GroupId   UUID       `json:"groupId"`
	Id        UUID       `json:"id"`
	MaxUses   int        `json:"maxUses"`
	Uses      int        `json:"uses"`
}

// InviteCodeRequest defines model for InviteCodeRequest.
type InviteCodeRequest struct {
	Code string `json:"code"`
}

// InvitePreview defines model for InvitePreview.
type InvitePreview struct {
	GroupAvatarUrl *string `json:"groupAvatarUrl"`
	GroupId        UUID    `json:"groupId"`
	GroupName      string  `json:"groupName"`
	MemberCount    *int    `json:"memberCount,omitempty"`
}

// InviteSummary defines model for InviteSummary.
type InviteSummary struct {
	CreatedAt Timestamp           `json:"createdAt"`
	ExpiresAt *Timestamp          `json:"expiresAt,omitempty"`
	GroupId   UUID                `json:"groupId"`
	Id        UUID                `json:"id"`
	MaxUses   int                 `json:"maxUses"`
	Status    InviteSummaryStatus `json:"status"`
	Uses      int                 `json:"uses"`
}

// InviteSummaryStatus defines model for InviteSummary.Status.
type InviteSummaryStatus string

// Round defines model for Round.
type Round struct {
	// ChainId EVM chain id
	ChainId ChainId `json:"chainId"`

	// ContractAddress EVM address (0x-prefixed, 40 hex chars)
	ContractAddress Address `json:"contractAddress"`

	// ContributionAmount Contribution amount in smallest units (string to avoid JSON number limits)
	ContributionAmount string    `json:"contributionAmount"`
	CreatedAt          Timestamp `json:"createdAt"`

	// CurrencySymbol e.g. USDC (optional)
	CurrencySymbol        *string     `json:"currencySymbol"`
	GroupId               UUID        `json:"groupId"`
	Id                    UUID        `json:"id"`
	PeriodDurationSeconds int         `json:"periodDurationSeconds"`
	Status                RoundStatus `json:"status"`
}

// RoundStatus defines model for Round.Status.
type RoundStatus string

// RoundDetail defines model for RoundDetail.
type RoundDetail struct {
	// ChainId EVM chain id
	ChainId ChainId `json:"chainId"`

	// ContractAddress EVM address (0x-prefixed, 40 hex chars)
	ContractAddress Address `json:"contractAddress"`

	// ContributionAmount Contribution amount in smallest units (string to avoid JSON number limits)
	ContributionAmount string    `json:"contributionAmount"`
	CreatedAt          Timestamp `json:"createdAt"`

	// CurrencySymbol e.g. USDC (optional)
	CurrencySymbol *string `json:"currencySymbol"`
	CurrentPeriod  *int    `json:"currentPeriod"`
	GroupId        UUID    `json:"groupId"`
	GroupName      string  `json:"groupName"`
	Id             UUID    `json:"id"`
	MemberCount    int     `json:"memberCount"`

	// NextPayoutAddress EVM address (0x-prefixed, 40 hex chars)
	NextPayoutAddress     *Address          `json:"nextPayoutAddress,omitempty"`
	PaidCount             *int              `json:"paidCount"`
	PeriodDurationSeconds int               `json:"periodDurationSeconds"`
	Status                RoundDetailStatus `json:"status"`

	// TotalContributed Total amount contributed so far (in smallest units)
	TotalContributed *string `json:"totalContributed"`
}

// RoundDetailStatus defines model for RoundDetail.Status.
type RoundDetailStatus string

// RoundPage defines model for RoundPage.
type RoundPage struct {
	Items      []RoundSummary `json:"items"`
	NextCursor *string        `json:"nextCursor"`
}

// RoundPeriodStatus defines model for RoundPeriodStatus.
type RoundPeriodStatus struct {
	EndTime *Timestamp `json:"endTime,omitempty"`

	// PaidAddresses Addresses that have contributed to this period
	PaidAddresses *[]Address `json:"paidAddresses,omitempty"`

	// PayoutAddress EVM address (0x-prefixed, 40 hex chars)
	PayoutAddress *Address `json:"payoutAddress,omitempty"`

	// PayoutTransactionHash Transaction hash of the payout
	PayoutTransactionHash *string `json:"payoutTransactionHash"`

	// Period Period number (0-indexed)
	Period    int                     `json:"period"`
	StartTime *Timestamp              `json:"startTime,omitempty"`
	Status    RoundPeriodStatusStatus `json:"status"`
}

// RoundPeriodStatusStatus defines model for RoundPeriodStatus.Status.
type RoundPeriodStatusStatus string

// RoundSummary defines model for RoundSummary.
type RoundSummary struct {
	// ChainId EVM chain id
	ChainId ChainId `json:"chainId"`

	// ContractAddress EVM address (0x-prefixed, 40 hex chars)
	ContractAddress Address `json:"contractAddress"`

	// ContributionAmount Contribution amount in smallest units (string to avoid JSON number limits)
	ContributionAmount string    `json:"contributionAmount"`
	CreatedAt          Timestamp `json:"createdAt"`

	// CurrencySymbol e.g. USDC (optional)
	CurrencySymbol        *string            `json:"currencySymbol"`
	CurrentPeriod         *int               `json:"currentPeriod"`
	GroupId               UUID               `json:"groupId"`
	GroupName             *string            `json:"groupName,omitempty"`
	Id                    UUID               `json:"id"`
	MemberCount           *int               `json:"memberCount"`
	PaidCount             *int               `json:"paidCount"`
	PeriodDurationSeconds int                `json:"periodDurationSeconds"`
	Status                RoundSummaryStatus `json:"status"`
}

// RoundSummaryStatus defines model for RoundSummary.Status.
type RoundSummaryStatus string

// Timestamp defines model for Timestamp.
type Timestamp = time.Time

// UUID defines model for UUID.
type UUID = openapi_types.UUID

// UpdateGroupRequest defines model for UpdateGroupRequest.
type UpdateGroupRequest struct {
	AvatarUrl   *string `json:"avatarUrl,omitempty"`
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// UpdateMeRequest defines model for UpdateMeRequest.
type UpdateMeRequest struct {
	AvatarUrl   *string `json:"avatarUrl,omitempty"`
	DisplayName *string `json:"displayName,omitempty"`
}

// User defines model for User.
type User struct {
	// Address EVM address (0x-prefixed, 40 hex chars)
	Address     Address    `json:"address"`
	AvatarUrl   *string    `json:"avatarUrl"`
	CreatedAt   Timestamp  `json:"createdAt"`
	DisplayName *string    `json:"displayName"`
	Id          UUID       `json:"id"`
	UpdatedAt   *Timestamp `json:"updatedAt,omitempty"`
}

// ListGroupsParams defines parameters for ListGroups.
type ListGroupsParams struct {
	// Q Optional search string for group name
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListGroupRoundsParams defines parameters for ListGroupRounds.
type ListGroupRoundsParams struct {
	Status *ListGroupRoundsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int                         `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string                      `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListGroupRoundsParamsStatus defines parameters for ListGroupRounds.
type ListGroupRoundsParamsStatus string

// ListRoundsParams defines parameters for ListRounds.
type ListRoundsParams struct {
	Status  *ListRoundsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	GroupId *UUID                   `form:"groupId,omitempty" json:"groupId,omitempty"`
	Limit   *int                    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor  *string                 `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListRoundsParamsStatus defines parameters for ListRounds.
type ListRoundsParamsStatus string

// GetRoundActivityParams defines parameters for GetRoundActivity.
type GetRoundActivityParams struct {
	Limit  *int                        `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string                     `form:"cursor,omitempty" json:"cursor,omitempty"`
	Type   *GetRoundActivityParamsType `form:"type,omitempty" json:"type,omitempty"`
}

// GetRoundActivityParamsType defines parameters for GetRoundActivity.
type GetRoundActivityParamsType string

// AuthNonceJSONRequestBody defines body for AuthNonce for application/json ContentType.
type AuthNonceJSONRequestBody = AuthNonceRequest

// AuthVerifyJSONRequestBody defines body for AuthVerify for application/json ContentType.
type AuthVerifyJSONRequestBody = AuthVerifyRequest

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = CreateGroupRequest

// UpdateGroupJSONRequestBody defines body for UpdateGroup for application/json ContentType.
type UpdateGroupJSONRequestBody = UpdateGroupRequest

// CreateInviteJSONRequestBody defines body for CreateInvite for application/json ContentType.
type CreateInviteJSONRequestBody = CreateInviteRequest

// CreateRoundJSONRequestBody defines body for CreateRound for application/json ContentType.
type CreateRoundJSONRequestBody = CreateRoundRequest

// AcceptInviteJSONRequestBody defines body for AcceptInvite for application/json ContentType.
type AcceptInviteJSONRequestBody = AcceptInviteRequest

// PreviewInviteJSONRequestBody defines body for PreviewInvite for application/json ContentType.
type PreviewInviteJSONRequestBody = InviteCodeRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateMeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Logout (clears session)
	// (POST /auth/logout)
	AuthLogout(ctx echo.Context) error
	// Request a nonce for wallet sign-in
	// (POST /auth/nonce)
	AuthNonce(ctx echo.Context) error
	// Verify wallet signature and create a session (sets HttpOnly cookie)
	// (POST /auth/verify)
	AuthVerify(ctx echo.Context) error
	// List groups the current user belongs to
	// (GET /groups)
	ListGroups(ctx echo.Context, params ListGroupsParams) error
	// Create a private group
	// (POST /groups)
	CreateGroup(ctx echo.Context) error
	// Get a group (members only)
	// (GET /groups/{groupId})
	GetGroup(ctx echo.Context, groupId UUID) error
	// Update group metadata (owner only)
	// (PATCH /groups/{groupId})
	UpdateGroup(ctx echo.Context, groupId UUID) error
	// List invites for a group (owner only)
	// (GET /groups/{groupId}/invites)
	ListInvites(ctx echo.Context, groupId UUID) error
	// Create an invite code (group owner only)
	// (POST /groups/{groupId}/invites)
	CreateInvite(ctx echo.Context, groupId UUID) error
	// Revoke an invite (owner only)
	// (DELETE /groups/{groupId}/invites/{inviteId})
	RevokeInvite(ctx echo.Context, groupId UUID, inviteId UUID) error
	// Leave a group (member only; owner cannot leave unless transfer ownership is supported)
	// (POST /groups/{groupId}/leave)
	LeaveGroup(ctx echo.Context, groupId UUID) error
	// List group members (members only)
	// (GET /groups/{groupId}/members)
	ListGroupMembers(ctx echo.Context, groupId UUID) error
	// Remove a member from a group (owner only)
	// (DELETE /groups/{groupId}/members/{memberAddress})
	RemoveGroupMember(ctx echo.Context, groupId UUID, memberAddress Address) error
	// List rounds for a group (members only)
	// (GET /groups/{groupId}/rounds)
	ListGroupRounds(ctx echo.Context, groupId UUID, params ListGroupRoundsParams) error
	// Create a round record for a group (members/owner; stores on-chain mapping)
	// (POST /groups/{groupId}/rounds)
	CreateRound(ctx echo.Context, groupId UUID) error
	// Accept an invite code to join a private group
	// (POST /invites/accept)
	AcceptInvite(ctx echo.Context) error
	// Preview an invite code (returns group info without joining)
	// (POST /invites/preview)
	PreviewInvite(ctx echo.Context) error
	// Get current user profile
	// (GET /me)
	GetMe(ctx echo.Context) error
	// Update current user profile
	// (PATCH /me)
	UpdateMe(ctx echo.Context) error
	// List rounds accessible to the current user
	// (GET /rounds)
	ListRounds(ctx echo.Context, params ListRoundsParams) error
	// Get round details (members only)
	// (GET /rounds/{roundId})
	GetRound(ctx echo.Context, roundId UUID) error
	// Get round activity feed (payments + payouts) (members only)
	// (GET /rounds/{roundId}/activity)
	GetRoundActivity(ctx echo.Context, roundId UUID, params GetRoundActivityParams) error
	// Get per-period contribution status (members only)
	// (GET /rounds/{roundId}/periods)
	GetRoundPeriods(ctx echo.Context, roundId UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// AuthLogout converts echo context to params.
func (w *ServerInterfaceWrapper) AuthLogout(ctx echo.Context) error {
	var err error

	ctx.Set(SessionAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AuthLogout(ctx)
	return err
}

// AuthNonce converts echo context to params.
func (w *ServerInterfaceWrapper) AuthNonce(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AuthNonce(ctx)
	return err
}

// AuthVerify converts echo context to params.
func (w *ServerInterfaceWrapper) AuthVerify(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AuthVerify(ctx)
	return err
}

// ListGroups converts echo context to params.
func (w *ServerInterfaceWrapper) ListGroups(ctx echo.Context) error {
	var err error

	ctx.Set(SessionAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", ctx.QueryParams(), &params.Q)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListGroups(ctx, params)
	return err
}

// CreateGroup converts echo context to params.
func (w *ServerInterfaceWrapper) CreateGroup(ctx echo.Context) error {
	var err error

	ctx.Set(SessionAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateGroup(ctx)
	return err
}

// GetGroup converts echo context to params.
func (w *ServerInterfaceWrapper) GetGroup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "groupId" -------------
	var groupId UUID

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", ctx.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupId: %s", err))
	}

	ctx.Set(SessionAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetGroup(ctx, groupId)
	return err
}

// UpdateGroup converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateGroup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "groupId" -------------
	var groupId UUID

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", ctx.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupId: %s", err))
	}

	ctx.Set(SessionAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateGroup(ctx, groupId)
	return err
}

// ListInvites converts echo context to params.
func (w *ServerInterfaceWrapper) ListInvites(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "groupId" -------------
	var groupId UUID

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", ctx.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupId: %s", err))
	}

	ctx.Set(SessionAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListInvites(ctx, groupId)
	return err
}

// CreateInvite converts echo context to params.
func (w *ServerInterfaceWrapper) CreateInvite(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "groupId" -------------
	var groupId UUID

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", ctx.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupId: %s", err))
	}

	ctx.Set(SessionAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateInvite(ctx, groupId)
	return err
}

// RevokeInvite converts echo context to params.
func (w *ServerInterfaceWrapper) RevokeInvite(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "groupId" -------------
	var groupId UUID

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", ctx.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupId: %s", err))
	}

	// ------------- Path parameter "inviteId" -------------
	var inviteId UUID

	err = runtime.BindStyledParameterWithOptions("simple", "inviteId", ctx.Param("inviteId"), &inviteId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter inviteId: %s", err))
	}

	ctx.Set(SessionAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RevokeInvite(ctx, groupId, inviteId)
	return err
}

// LeaveGroup converts echo context to params.
func (w *ServerInterfaceWrapper) LeaveGroup(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "groupId" -------------
	var groupId UUID

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", ctx.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupId: %s", err))
	}

	ctx.Set(SessionAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.LeaveGroup(ctx, groupId)
	return err
}

// ListGroupMembers converts echo context to params.
func (w *ServerInterfaceWrapper) ListGroupMembers(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "groupId" -------------
	var groupId UUID

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", ctx.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupId: %s", err))
	}

	ctx.Set(SessionAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListGroupMembers(ctx, groupId)
	return err
}

// RemoveGroupMember converts echo context to params.
func (w *ServerInterfaceWrapper) RemoveGroupMember(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "groupId" -------------
	var groupId UUID

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", ctx.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupId: %s", err))
	}

	// ------------- Path parameter "memberAddress" -------------
	var memberAddress Address

	err = runtime.BindStyledParameterWithOptions("simple", "memberAddress", ctx.Param("memberAddress"), &memberAddress, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter memberAddress: %s", err))
	}

	ctx.Set(SessionAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RemoveGroupMember(ctx, groupId, memberAddress)
	return err
}

// ListGroupRounds converts echo context to params.
func (w *ServerInterfaceWrapper) ListGroupRounds(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "groupId" -------------
	var groupId UUID

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", ctx.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupId: %s", err))
	}

	ctx.Set(SessionAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupRoundsParams
	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListGroupRounds(ctx, groupId, params)
	return err
}

// CreateRound converts echo context to params.
func (w *ServerInterfaceWrapper) CreateRound(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "groupId" -------------
	var groupId UUID

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", ctx.Param("groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupId: %s", err))
	}

	ctx.Set(SessionAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateRound(ctx, groupId)
	return err
}

// AcceptInvite converts echo context to params.
func (w *ServerInterfaceWrapper) AcceptInvite(ctx echo.Context) error {
	var err error

	ctx.Set(SessionAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AcceptInvite(ctx)
	return err
}

// PreviewInvite converts echo context to params.
func (w *ServerInterfaceWrapper) PreviewInvite(ctx echo.Context) error {
	var err error

	ctx.Set(SessionAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PreviewInvite(ctx)
	return err
}

// GetMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetMe(ctx echo.Context) error {
	var err error

	ctx.Set(SessionAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMe(ctx)
	return err
}

// UpdateMe converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateMe(ctx echo.Context) error {
	var err error

	ctx.Set(SessionAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateMe(ctx)
	return err
}

// ListRounds converts echo context to params.
func (w *ServerInterfaceWrapper) ListRounds(ctx echo.Context) error {
	var err error

	ctx.Set(SessionAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRoundsParams
	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "groupId" -------------

	err = runtime.BindQueryParameter("form", true, false, "groupId", ctx.QueryParams(), &params.GroupId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter groupId: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListRounds(ctx, params)
	return err
}

// GetRound converts echo context to params.
func (w *ServerInterfaceWrapper) GetRound(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "roundId" -------------
	var roundId UUID

	err = runtime.BindStyledParameterWithOptions("simple", "roundId", ctx.Param("roundId"), &roundId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter roundId: %s", err))
	}

	ctx.Set(SessionAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetRound(ctx, roundId)
	return err
}

// GetRoundActivity converts echo context to params.
func (w *ServerInterfaceWrapper) GetRoundActivity(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "roundId" -------------
	var roundId UUID

	err = runtime.BindStyledParameterWithOptions("simple", "roundId", ctx.Param("roundId"), &roundId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter roundId: %s", err))
	}

	ctx.Set(SessionAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRoundActivityParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", ctx.QueryParams(), &params.Type)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetRoundActivity(ctx, roundId, params)
	return err
}

// GetRoundPeriods converts echo context to params.
func (w *ServerInterfaceWrapper) GetRoundPeriods(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "roundId" -------------
	var roundId UUID

	err = runtime.BindStyledParameterWithOptions("simple", "roundId", ctx.Param("roundId"), &roundId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter roundId: %s", err))
	}

	ctx.Set(SessionAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetRoundPeriods(ctx, roundId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/auth/logout", wrapper.AuthLogout)
	router.POST(baseURL+"/auth/nonce", wrapper.AuthNonce)
	router.POST(baseURL+"/auth/verify", wrapper.AuthVerify)
	router.GET(baseURL+"/groups", wrapper.ListGroups)
	router.POST(baseURL+"/groups", wrapper.CreateGroup)
	router.GET(baseURL+"/groups/:groupId", wrapper.GetGroup)
	router.PATCH(baseURL+"/groups/:groupId", wrapper.UpdateGroup)
	router.GET(baseURL+"/groups/:groupId/invites", wrapper.ListInvites)
	router.POST(baseURL+"/groups/:groupId/invites", wrapper.CreateInvite)
	router.DELETE(baseURL+"/groups/:groupId/invites/:inviteId", wrapper.RevokeInvite)
	router.POST(baseURL+"/groups/:groupId/leave", wrapper.LeaveGroup)
	router.GET(baseURL+"/groups/:groupId/members", wrapper.ListGroupMembers)
	router.DELETE(baseURL+"/groups/:groupId/members/:memberAddress", wrapper.RemoveGroupMember)
	router.GET(baseURL+"/groups/:groupId/rounds", wrapper.ListGroupRounds)
	router.POST(baseURL+"/groups/:groupId/rounds", wrapper.CreateRound)
	router.POST(baseURL+"/invites/accept", wrapper.AcceptInvite)
	router.POST(baseURL+"/invites/preview", wrapper.PreviewInvite)
	router.GET(baseURL+"/me", wrapper.GetMe)
	router.PATCH(baseURL+"/me", wrapper.UpdateMe)
	router.GET(baseURL+"/rounds", wrapper.ListRounds)
	router.GET(baseURL+"/rounds/:roundId", wrapper.GetRound)
	router.GET(baseURL+"/rounds/:roundId/activity", wrapper.GetRoundActivity)
	router.GET(baseURL+"/rounds/:roundId/periods", wrapper.GetRoundPeriods)

}

type AuthLogoutRequestObject struct {
}

type AuthLogoutResponseObject interface {
	VisitAuthLogoutResponse(w http.ResponseWriter) error
}

type AuthLogout204Response struct {
}

func (response AuthLogout204Response) VisitAuthLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type AuthLogout401JSONResponse ErrorUnauthorized

func (response AuthLogout401JSONResponse) VisitAuthLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AuthLogout500JSONResponse ErrorInternalServerError

func (response AuthLogout500JSONResponse) VisitAuthLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AuthNonceRequestObject struct {
	Body *AuthNonceJSONRequestBody
}

type AuthNonceResponseObject interface {
	VisitAuthNonceResponse(w http.ResponseWriter) error
}

type AuthNonce200JSONResponse AuthNonceResponse

func (response AuthNonce200JSONResponse) VisitAuthNonceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AuthNonce400JSONResponse ErrorBadRequest

func (response AuthNonce400JSONResponse) VisitAuthNonceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AuthVerifyRequestObject struct {
	Body *AuthVerifyJSONRequestBody
}

type AuthVerifyResponseObject interface {
	VisitAuthVerifyResponse(w http.ResponseWriter) error
}

type AuthVerify200ResponseHeaders struct {
	SetCookie string
}

type AuthVerify200JSONResponse struct {
	Body    AuthVerifyResponse
	Headers AuthVerify200ResponseHeaders
}

func (response AuthVerify200JSONResponse) VisitAuthVerifyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type AuthVerify400JSONResponse ErrorBadRequest

func (response AuthVerify400JSONResponse) VisitAuthVerifyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AuthVerify401JSONResponse ErrorUnauthorized

func (response AuthVerify401JSONResponse) VisitAuthVerifyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListGroupsRequestObject struct {
	Params ListGroupsParams
}

type ListGroupsResponseObject interface {
	VisitListGroupsResponse(w http.ResponseWriter) error
}

type ListGroups200JSONResponse GroupPage

func (response ListGroups200JSONResponse) VisitListGroupsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListGroups401JSONResponse ErrorUnauthorized

func (response ListGroups401JSONResponse) VisitListGroupsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListGroups500JSONResponse ErrorInternalServerError

func (response ListGroups500JSONResponse) VisitListGroupsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateGroupRequestObject struct {
	Body *CreateGroupJSONRequestBody
}

type CreateGroupResponseObject interface {
	VisitCreateGroupResponse(w http.ResponseWriter) error
}

type CreateGroup201JSONResponse Group

func (response CreateGroup201JSONResponse) VisitCreateGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateGroup400JSONResponse ErrorBadRequest

func (response CreateGroup400JSONResponse) VisitCreateGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateGroup401JSONResponse ErrorUnauthorized

func (response CreateGroup401JSONResponse) VisitCreateGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateGroup500JSONResponse ErrorInternalServerError

func (response CreateGroup500JSONResponse) VisitCreateGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetGroupRequestObject struct {
	GroupId UUID `json:"groupId"`
}

type GetGroupResponseObject interface {
	VisitGetGroupResponse(w http.ResponseWriter) error
}

type GetGroup200JSONResponse Group

func (response GetGroup200JSONResponse) VisitGetGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetGroup401JSONResponse ErrorUnauthorized

func (response GetGroup401JSONResponse) VisitGetGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetGroup403JSONResponse ErrorForbidden

func (response GetGroup403JSONResponse) VisitGetGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetGroup404JSONResponse ErrorNotFound

func (response GetGroup404JSONResponse) VisitGetGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetGroup500JSONResponse ErrorInternalServerError

func (response GetGroup500JSONResponse) VisitGetGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateGroupRequestObject struct {
	GroupId UUID `json:"groupId"`
	Body    *UpdateGroupJSONRequestBody
}

type UpdateGroupResponseObject interface {
	VisitUpdateGroupResponse(w http.ResponseWriter) error
}

type UpdateGroup200JSONResponse Group

func (response UpdateGroup200JSONResponse) VisitUpdateGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateGroup400JSONResponse ErrorBadRequest

func (response UpdateGroup400JSONResponse) VisitUpdateGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateGroup401JSONResponse ErrorUnauthorized

func (response UpdateGroup401JSONResponse) VisitUpdateGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateGroup403JSONResponse ErrorForbidden

func (response UpdateGroup403JSONResponse) VisitUpdateGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateGroup404JSONResponse ErrorNotFound

func (response UpdateGroup404JSONResponse) VisitUpdateGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateGroup500JSONResponse ErrorInternalServerError

func (response UpdateGroup500JSONResponse) VisitUpdateGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListInvitesRequestObject struct {
	GroupId UUID `json:"groupId"`
}

type ListInvitesResponseObject interface {
	VisitListInvitesResponse(w http.ResponseWriter) error
}

type ListInvites200JSONResponse []InviteSummary

func (response ListInvites200JSONResponse) VisitListInvitesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListInvites401JSONResponse ErrorUnauthorized

func (response ListInvites401JSONResponse) VisitListInvitesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListInvites403JSONResponse ErrorForbidden

func (response ListInvites403JSONResponse) VisitListInvitesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListInvites404JSONResponse ErrorNotFound

func (response ListInvites404JSONResponse) VisitListInvitesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListInvites500JSONResponse ErrorInternalServerError

func (response ListInvites500JSONResponse) VisitListInvitesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateInviteRequestObject struct {
	GroupId UUID `json:"groupId"`
	Body    *CreateInviteJSONRequestBody
}

type CreateInviteResponseObject interface {
	VisitCreateInviteResponse(w http.ResponseWriter) error
}

type CreateInvite201JSONResponse Invite

func (response CreateInvite201JSONResponse) VisitCreateInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateInvite400JSONResponse ErrorBadRequest

func (response CreateInvite400JSONResponse) VisitCreateInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateInvite401JSONResponse ErrorUnauthorized

func (response CreateInvite401JSONResponse) VisitCreateInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateInvite403JSONResponse ErrorForbidden

func (response CreateInvite403JSONResponse) VisitCreateInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateInvite404JSONResponse ErrorNotFound

func (response CreateInvite404JSONResponse) VisitCreateInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateInvite500JSONResponse ErrorInternalServerError

func (response CreateInvite500JSONResponse) VisitCreateInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RevokeInviteRequestObject struct {
	GroupId  UUID `json:"groupId"`
	InviteId UUID `json:"inviteId"`
}

type RevokeInviteResponseObject interface {
	VisitRevokeInviteResponse(w http.ResponseWriter) error
}

type RevokeInvite204Response struct {
}

func (response RevokeInvite204Response) VisitRevokeInviteResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeInvite401JSONResponse ErrorUnauthorized

func (response RevokeInvite401JSONResponse) VisitRevokeInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RevokeInvite403JSONResponse ErrorForbidden

func (response RevokeInvite403JSONResponse) VisitRevokeInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type RevokeInvite404JSONResponse ErrorNotFound

func (response RevokeInvite404JSONResponse) VisitRevokeInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RevokeInvite500JSONResponse ErrorInternalServerError

func (response RevokeInvite500JSONResponse) VisitRevokeInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LeaveGroupRequestObject struct {
	GroupId UUID `json:"groupId"`
}

type LeaveGroupResponseObject interface {
	VisitLeaveGroupResponse(w http.ResponseWriter) error
}

type LeaveGroup204Response struct {
}

func (response LeaveGroup204Response) VisitLeaveGroupResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type LeaveGroup401JSONResponse ErrorUnauthorized

func (response LeaveGroup401JSONResponse) VisitLeaveGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LeaveGroup403JSONResponse ErrorForbidden

func (response LeaveGroup403JSONResponse) VisitLeaveGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type LeaveGroup404JSONResponse ErrorNotFound

func (response LeaveGroup404JSONResponse) VisitLeaveGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type LeaveGroup500JSONResponse ErrorInternalServerError

func (response LeaveGroup500JSONResponse) VisitLeaveGroupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListGroupMembersRequestObject struct {
	GroupId UUID `json:"groupId"`
}

type ListGroupMembersResponseObject interface {
	VisitListGroupMembersResponse(w http.ResponseWriter) error
}

type ListGroupMembers200JSONResponse []GroupMember

func (response ListGroupMembers200JSONResponse) VisitListGroupMembersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListGroupMembers401JSONResponse ErrorUnauthorized

func (response ListGroupMembers401JSONResponse) VisitListGroupMembersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListGroupMembers403JSONResponse ErrorForbidden

func (response ListGroupMembers403JSONResponse) VisitListGroupMembersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListGroupMembers404JSONResponse ErrorNotFound

func (response ListGroupMembers404JSONResponse) VisitListGroupMembersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListGroupMembers500JSONResponse ErrorInternalServerError

func (response ListGroupMembers500JSONResponse) VisitListGroupMembersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RemoveGroupMemberRequestObject struct {
	GroupId       UUID    `json:"groupId"`
	MemberAddress Address `json:"memberAddress"`
}

type RemoveGroupMemberResponseObject interface {
	VisitRemoveGroupMemberResponse(w http.ResponseWriter) error
}

type RemoveGroupMember204Response struct {
}

func (response RemoveGroupMember204Response) VisitRemoveGroupMemberResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RemoveGroupMember401JSONResponse ErrorUnauthorized

func (response RemoveGroupMember401JSONResponse) VisitRemoveGroupMemberResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RemoveGroupMember403JSONResponse ErrorForbidden

func (response RemoveGroupMember403JSONResponse) VisitRemoveGroupMemberResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type RemoveGroupMember404JSONResponse ErrorNotFound

func (response RemoveGroupMember404JSONResponse) VisitRemoveGroupMemberResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RemoveGroupMember500JSONResponse ErrorInternalServerError

func (response RemoveGroupMember500JSONResponse) VisitRemoveGroupMemberResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListGroupRoundsRequestObject struct {
	GroupId UUID `json:"groupId"`
	Params  ListGroupRoundsParams
}

type ListGroupRoundsResponseObject interface {
	VisitListGroupRoundsResponse(w http.ResponseWriter) error
}

type ListGroupRounds200JSONResponse RoundPage

func (response ListGroupRounds200JSONResponse) VisitListGroupRoundsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListGroupRounds401JSONResponse ErrorUnauthorized

func (response ListGroupRounds401JSONResponse) VisitListGroupRoundsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListGroupRounds403JSONResponse ErrorForbidden

func (response ListGroupRounds403JSONResponse) VisitListGroupRoundsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListGroupRounds404JSONResponse ErrorNotFound

func (response ListGroupRounds404JSONResponse) VisitListGroupRoundsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListGroupRounds500JSONResponse ErrorInternalServerError

func (response ListGroupRounds500JSONResponse) VisitListGroupRoundsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateRoundRequestObject struct {
	GroupId UUID `json:"groupId"`
	Body    *CreateRoundJSONRequestBody
}

type CreateRoundResponseObject interface {
	VisitCreateRoundResponse(w http.ResponseWriter) error
}

type CreateRound201JSONResponse Round

func (response CreateRound201JSONResponse) VisitCreateRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateRound400JSONResponse ErrorBadRequest

func (response CreateRound400JSONResponse) VisitCreateRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateRound401JSONResponse ErrorUnauthorized

func (response CreateRound401JSONResponse) VisitCreateRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateRound403JSONResponse ErrorForbidden

func (response CreateRound403JSONResponse) VisitCreateRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateRound404JSONResponse ErrorNotFound

func (response CreateRound404JSONResponse) VisitCreateRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateRound500JSONResponse ErrorInternalServerError

func (response CreateRound500JSONResponse) VisitCreateRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AcceptInviteRequestObject struct {
	Body *AcceptInviteJSONRequestBody
}

type AcceptInviteResponseObject interface {
	VisitAcceptInviteResponse(w http.ResponseWriter) error
}

type AcceptInvite200JSONResponse AcceptInviteResponse

func (response AcceptInvite200JSONResponse) VisitAcceptInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AcceptInvite400JSONResponse ErrorBadRequest

func (response AcceptInvite400JSONResponse) VisitAcceptInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AcceptInvite401JSONResponse ErrorUnauthorized

func (response AcceptInvite401JSONResponse) VisitAcceptInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AcceptInvite404JSONResponse ErrorNotFound

func (response AcceptInvite404JSONResponse) VisitAcceptInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AcceptInvite500JSONResponse ErrorInternalServerError

func (response AcceptInvite500JSONResponse) VisitAcceptInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PreviewInviteRequestObject struct {
	Body *PreviewInviteJSONRequestBody
}

type PreviewInviteResponseObject interface {
	VisitPreviewInviteResponse(w http.ResponseWriter) error
}

type PreviewInvite200JSONResponse InvitePreview

func (response PreviewInvite200JSONResponse) VisitPreviewInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PreviewInvite400JSONResponse ErrorBadRequest

func (response PreviewInvite400JSONResponse) VisitPreviewInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PreviewInvite404JSONResponse ErrorNotFound

func (response PreviewInvite404JSONResponse) VisitPreviewInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse User

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMe401JSONResponse ErrorUnauthorized

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateMeRequestObject struct {
	Body *UpdateMeJSONRequestBody
}

type UpdateMeResponseObject interface {
	VisitUpdateMeResponse(w http.ResponseWriter) error
}

type UpdateMe200JSONResponse User

func (response UpdateMe200JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateMe400JSONResponse ErrorBadRequest

func (response UpdateMe400JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateMe401JSONResponse ErrorUnauthorized

func (response UpdateMe401JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateMe500JSONResponse ErrorInternalServerError

func (response UpdateMe500JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListRoundsRequestObject struct {
	Params ListRoundsParams
}

type ListRoundsResponseObject interface {
	VisitListRoundsResponse(w http.ResponseWriter) error
}

type ListRounds200JSONResponse RoundPage

func (response ListRounds200JSONResponse) VisitListRoundsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListRounds401JSONResponse ErrorUnauthorized

func (response ListRounds401JSONResponse) VisitListRoundsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListRounds500JSONResponse ErrorInternalServerError

func (response ListRounds500JSONResponse) VisitListRoundsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetRoundRequestObject struct {
	RoundId UUID `json:"roundId"`
}

type GetRoundResponseObject interface {
	VisitGetRoundResponse(w http.ResponseWriter) error
}

type GetRound200JSONResponse RoundDetail

func (response GetRound200JSONResponse) VisitGetRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRound401JSONResponse ErrorUnauthorized

func (response GetRound401JSONResponse) VisitGetRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetRound403JSONResponse ErrorForbidden

func (response GetRound403JSONResponse) VisitGetRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetRound404JSONResponse ErrorNotFound

func (response GetRound404JSONResponse) VisitGetRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetRound500JSONResponse ErrorInternalServerError

func (response GetRound500JSONResponse) VisitGetRoundResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetRoundActivityRequestObject struct {
	RoundId UUID `json:"roundId"`
	Params  GetRoundActivityParams
}

type GetRoundActivityResponseObject interface {
	VisitGetRoundActivityResponse(w http.ResponseWriter) error
}

type GetRoundActivity200JSONResponse ActivityPage

func (response GetRoundActivity200JSONResponse) VisitGetRoundActivityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRoundActivity401JSONResponse ErrorUnauthorized

func (response GetRoundActivity401JSONResponse) VisitGetRoundActivityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetRoundActivity403JSONResponse ErrorForbidden

func (response GetRoundActivity403JSONResponse) VisitGetRoundActivityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetRoundActivity404JSONResponse ErrorNotFound

func (response GetRoundActivity404JSONResponse) VisitGetRoundActivityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetRoundActivity500JSONResponse ErrorInternalServerError

func (response GetRoundActivity500JSONResponse) VisitGetRoundActivityResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetRoundPeriodsRequestObject struct {
	RoundId UUID `json:"roundId"`
}

type GetRoundPeriodsResponseObject interface {
	VisitGetRoundPeriodsResponse(w http.ResponseWriter) error
}

type GetRoundPeriods200JSONResponse []RoundPeriodStatus

func (response GetRoundPeriods200JSONResponse) VisitGetRoundPeriodsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRoundPeriods401JSONResponse ErrorUnauthorized

func (response GetRoundPeriods401JSONResponse) VisitGetRoundPeriodsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetRoundPeriods403JSONResponse ErrorForbidden

func (response GetRoundPeriods403JSONResponse) VisitGetRoundPeriodsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetRoundPeriods404JSONResponse ErrorNotFound

func (response GetRoundPeriods404JSONResponse) VisitGetRoundPeriodsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetRoundPeriods500JSONResponse ErrorInternalServerError

func (response GetRoundPeriods500JSONResponse) VisitGetRoundPeriodsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Logout (clears session)
	// (POST /auth/logout)
	AuthLogout(ctx context.Context, request AuthLogoutRequestObject) (AuthLogoutResponseObject, error)
	// Request a nonce for wallet sign-in
	// (POST /auth/nonce)
	AuthNonce(ctx context.Context, request AuthNonceRequestObject) (AuthNonceResponseObject, error)
	// Verify wallet signature and create a session (sets HttpOnly cookie)
	// (POST /auth/verify)
	AuthVerify(ctx context.Context, request AuthVerifyRequestObject) (AuthVerifyResponseObject, error)
	// List groups the current user belongs to
	// (GET /groups)
	ListGroups(ctx context.Context, request ListGroupsRequestObject) (ListGroupsResponseObject, error)
	// Create a private group
	// (POST /groups)
	CreateGroup(ctx context.Context, request CreateGroupRequestObject) (CreateGroupResponseObject, error)
	// Get a group (members only)
	// (GET /groups/{groupId})
	GetGroup(ctx context.Context, request GetGroupRequestObject) (GetGroupResponseObject, error)
	// Update group metadata (owner only)
	// (PATCH /groups/{groupId})
	UpdateGroup(ctx context.Context, request UpdateGroupRequestObject) (UpdateGroupResponseObject, error)
	// List invites for a group (owner only)
	// (GET /groups/{groupId}/invites)
	ListInvites(ctx context.Context, request ListInvitesRequestObject) (ListInvitesResponseObject, error)
	// Create an invite code (group owner only)
	// (POST /groups/{groupId}/invites)
	CreateInvite(ctx context.Context, request CreateInviteRequestObject) (CreateInviteResponseObject, error)
	// Revoke an invite (owner only)
	// (DELETE /groups/{groupId}/invites/{inviteId})
	RevokeInvite(ctx context.Context, request RevokeInviteRequestObject) (RevokeInviteResponseObject, error)
	// Leave a group (member only; owner cannot leave unless transfer ownership is supported)
	// (POST /groups/{groupId}/leave)
	LeaveGroup(ctx context.Context, request LeaveGroupRequestObject) (LeaveGroupResponseObject, error)
	// List group members (members only)
	// (GET /groups/{groupId}/members)
	ListGroupMembers(ctx context.Context, request ListGroupMembersRequestObject) (ListGroupMembersResponseObject, error)
	// Remove a member from a group (owner only)
	// (DELETE /groups/{groupId}/members/{memberAddress})
	RemoveGroupMember(ctx context.Context, request RemoveGroupMemberRequestObject) (RemoveGroupMemberResponseObject, error)
	// List rounds for a group (members only)
	// (GET /groups/{groupId}/rounds)
	ListGroupRounds(ctx context.Context, request ListGroupRoundsRequestObject) (ListGroupRoundsResponseObject, error)
	// Create a round record for a group (members/owner; stores on-chain mapping)
	// (POST /groups/{groupId}/rounds)
	CreateRound(ctx context.Context, request CreateRoundRequestObject) (CreateRoundResponseObject, error)
	// Accept an invite code to join a private group
	// (POST /invites/accept)
	AcceptInvite(ctx context.Context, request AcceptInviteRequestObject) (AcceptInviteResponseObject, error)
	// Preview an invite code (returns group info without joining)
	// (POST /invites/preview)
	PreviewInvite(ctx context.Context, request PreviewInviteRequestObject) (PreviewInviteResponseObject, error)
	// Get current user profile
	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// Update current user profile
	// (PATCH /me)
	UpdateMe(ctx context.Context, request UpdateMeRequestObject) (UpdateMeResponseObject, error)
	// List rounds accessible to the current user
	// (GET /rounds)
	ListRounds(ctx context.Context, request ListRoundsRequestObject) (ListRoundsResponseObject, error)
	// Get round details (members only)
	// (GET /rounds/{roundId})
	GetRound(ctx context.Context, request GetRoundRequestObject) (GetRoundResponseObject, error)
	// Get round activity feed (payments + payouts) (members only)
	// (GET /rounds/{roundId}/activity)
	GetRoundActivity(ctx context.Context, request GetRoundActivityRequestObject) (GetRoundActivityResponseObject, error)
	// Get per-period contribution status (members only)
	// (GET /rounds/{roundId}/periods)
	GetRoundPeriods(ctx context.Context, request GetRoundPeriodsRequestObject) (GetRoundPeriodsResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// AuthLogout operation middleware
func (sh *strictHandler) AuthLogout(ctx echo.Context) error {
	var request AuthLogoutRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AuthLogout(ctx.Request().Context(), request.(AuthLogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthLogout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AuthLogoutResponseObject); ok {
		return validResponse.VisitAuthLogoutResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AuthNonce operation middleware
func (sh *strictHandler) AuthNonce(ctx echo.Context) error {
	var request AuthNonceRequestObject

	var body AuthNonceJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AuthNonce(ctx.Request().Context(), request.(AuthNonceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthNonce")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AuthNonceResponseObject); ok {
		return validResponse.VisitAuthNonceResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AuthVerify operation middleware
func (sh *strictHandler) AuthVerify(ctx echo.Context) error {
	var request AuthVerifyRequestObject

	var body AuthVerifyJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AuthVerify(ctx.Request().Context(), request.(AuthVerifyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthVerify")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AuthVerifyResponseObject); ok {
		return validResponse.VisitAuthVerifyResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListGroups operation middleware
func (sh *strictHandler) ListGroups(ctx echo.Context, params ListGroupsParams) error {
	var request ListGroupsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListGroups(ctx.Request().Context(), request.(ListGroupsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListGroups")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListGroupsResponseObject); ok {
		return validResponse.VisitListGroupsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateGroup operation middleware
func (sh *strictHandler) CreateGroup(ctx echo.Context) error {
	var request CreateGroupRequestObject

	var body CreateGroupJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateGroup(ctx.Request().Context(), request.(CreateGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateGroup")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateGroupResponseObject); ok {
		return validResponse.VisitCreateGroupResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetGroup operation middleware
func (sh *strictHandler) GetGroup(ctx echo.Context, groupId UUID) error {
	var request GetGroupRequestObject

	request.GroupId = groupId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetGroup(ctx.Request().Context(), request.(GetGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetGroup")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetGroupResponseObject); ok {
		return validResponse.VisitGetGroupResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateGroup operation middleware
func (sh *strictHandler) UpdateGroup(ctx echo.Context, groupId UUID) error {
	var request UpdateGroupRequestObject

	request.GroupId = groupId

	var body UpdateGroupJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateGroup(ctx.Request().Context(), request.(UpdateGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateGroup")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateGroupResponseObject); ok {
		return validResponse.VisitUpdateGroupResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListInvites operation middleware
func (sh *strictHandler) ListInvites(ctx echo.Context, groupId UUID) error {
	var request ListInvitesRequestObject

	request.GroupId = groupId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListInvites(ctx.Request().Context(), request.(ListInvitesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListInvites")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListInvitesResponseObject); ok {
		return validResponse.VisitListInvitesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateInvite operation middleware
func (sh *strictHandler) CreateInvite(ctx echo.Context, groupId UUID) error {
	var request CreateInviteRequestObject

	request.GroupId = groupId

	var body CreateInviteJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateInvite(ctx.Request().Context(), request.(CreateInviteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateInvite")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateInviteResponseObject); ok {
		return validResponse.VisitCreateInviteResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RevokeInvite operation middleware
func (sh *strictHandler) RevokeInvite(ctx echo.Context, groupId UUID, inviteId UUID) error {
	var request RevokeInviteRequestObject

	request.GroupId = groupId
	request.InviteId = inviteId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeInvite(ctx.Request().Context(), request.(RevokeInviteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeInvite")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RevokeInviteResponseObject); ok {
		return validResponse.VisitRevokeInviteResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// LeaveGroup operation middleware
func (sh *strictHandler) LeaveGroup(ctx echo.Context, groupId UUID) error {
	var request LeaveGroupRequestObject

	request.GroupId = groupId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.LeaveGroup(ctx.Request().Context(), request.(LeaveGroupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LeaveGroup")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LeaveGroupResponseObject); ok {
		return validResponse.VisitLeaveGroupResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListGroupMembers operation middleware
func (sh *strictHandler) ListGroupMembers(ctx echo.Context, groupId UUID) error {
	var request ListGroupMembersRequestObject

	request.GroupId = groupId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListGroupMembers(ctx.Request().Context(), request.(ListGroupMembersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListGroupMembers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListGroupMembersResponseObject); ok {
		return validResponse.VisitListGroupMembersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RemoveGroupMember operation middleware
func (sh *strictHandler) RemoveGroupMember(ctx echo.Context, groupId UUID, memberAddress Address) error {
	var request RemoveGroupMemberRequestObject

	request.GroupId = groupId
	request.MemberAddress = memberAddress

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RemoveGroupMember(ctx.Request().Context(), request.(RemoveGroupMemberRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RemoveGroupMember")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RemoveGroupMemberResponseObject); ok {
		return validResponse.VisitRemoveGroupMemberResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListGroupRounds operation middleware
func (sh *strictHandler) ListGroupRounds(ctx echo.Context, groupId UUID, params ListGroupRoundsParams) error {
	var request ListGroupRoundsRequestObject

	request.GroupId = groupId
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListGroupRounds(ctx.Request().Context(), request.(ListGroupRoundsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListGroupRounds")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListGroupRoundsResponseObject); ok {
		return validResponse.VisitListGroupRoundsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateRound operation middleware
func (sh *strictHandler) CreateRound(ctx echo.Context, groupId UUID) error {
	var request CreateRoundRequestObject

	request.GroupId = groupId

	var body CreateRoundJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateRound(ctx.Request().Context(), request.(CreateRoundRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateRound")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateRoundResponseObject); ok {
		return validResponse.VisitCreateRoundResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AcceptInvite operation middleware
func (sh *strictHandler) AcceptInvite(ctx echo.Context) error {
	var request AcceptInviteRequestObject

	var body AcceptInviteJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AcceptInvite(ctx.Request().Context(), request.(AcceptInviteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AcceptInvite")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AcceptInviteResponseObject); ok {
		return validResponse.VisitAcceptInviteResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PreviewInvite operation middleware
func (sh *strictHandler) PreviewInvite(ctx echo.Context) error {
	var request PreviewInviteRequestObject

	var body PreviewInviteJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PreviewInvite(ctx.Request().Context(), request.(PreviewInviteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PreviewInvite")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PreviewInviteResponseObject); ok {
		return validResponse.VisitPreviewInviteResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(ctx echo.Context) error {
	var request GetMeRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx.Request().Context(), request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		return validResponse.VisitGetMeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateMe operation middleware
func (sh *strictHandler) UpdateMe(ctx echo.Context) error {
	var request UpdateMeRequestObject

	var body UpdateMeJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMe(ctx.Request().Context(), request.(UpdateMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateMeResponseObject); ok {
		return validResponse.VisitUpdateMeResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListRounds operation middleware
func (sh *strictHandler) ListRounds(ctx echo.Context, params ListRoundsParams) error {
	var request ListRoundsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListRounds(ctx.Request().Context(), request.(ListRoundsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRounds")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListRoundsResponseObject); ok {
		return validResponse.VisitListRoundsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetRound operation middleware
func (sh *strictHandler) GetRound(ctx echo.Context, roundId UUID) error {
	var request GetRoundRequestObject

	request.RoundId = roundId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetRound(ctx.Request().Context(), request.(GetRoundRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRound")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetRoundResponseObject); ok {
		return validResponse.VisitGetRoundResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetRoundActivity operation middleware
func (sh *strictHandler) GetRoundActivity(ctx echo.Context, roundId UUID, params GetRoundActivityParams) error {
	var request GetRoundActivityRequestObject

	request.RoundId = roundId
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetRoundActivity(ctx.Request().Context(), request.(GetRoundActivityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRoundActivity")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetRoundActivityResponseObject); ok {
		return validResponse.VisitGetRoundActivityResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetRoundPeriods operation middleware
func (sh *strictHandler) GetRoundPeriods(ctx echo.Context, roundId UUID) error {
	var request GetRoundPeriodsRequestObject

	request.RoundId = roundId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetRoundPeriods(ctx.Request().Context(), request.(GetRoundPeriodsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRoundPeriods")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetRoundPeriodsResponseObject); ok {
		return validResponse.VisitGetRoundPeriodsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
